"""Move PDFs from an output directory into a 02_matched_pdfs folder if they exist in a reference directory."""

from __future__ import annotations

import argparse
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Set


PDF_EXTENSION = ".pdf"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare PDFs in an output directory against a reference directory and "
            "move matches into a 02_matched_pdfs directory."
        )
    )
    parser.add_argument(
        "output_dir",
        type=Path,
        help="Directory containing PDFs generated by folder2pdf",
    )
    parser.add_argument(
        "reference_dir",
        type=Path,
        help="Directory containing PDFs produced by the OCR tool",
    )
    parser.add_argument(
        "--destination",
        type=Path,
        default=None,
        help="Destination directory for matched PDFs (default: <output_dir>/../02_matched_pdfs)",
    )
    return parser.parse_args()


def ensure_directory(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"Directory not found: {path}")
    if not path.is_dir():
        raise NotADirectoryError(f"Expected directory but found file: {path}")
    return path


def pdf_names(directory: Path) -> Set[str]:
    return {
        file.name
        for file in directory.iterdir()
        if file.is_file() and file.suffix.lower() == PDF_EXTENSION
    }


@dataclass
class MoveStats:
    moved: int = 0
    skipped_missing: int = 0
    skipped_conflict: int = 0

    def log_summary(self) -> None:
        logging.info(
            "Summary: %d moved, %d missing in reference, %d skipped due to conflicts",
            self.moved,
            self.skipped_missing,
            self.skipped_conflict,
        )


def move_matching_pdfs(source: Path, reference: Path, destination: Path) -> MoveStats:
    ensure_directory(source)
    ensure_directory(reference)
    destination.mkdir(parents=True, exist_ok=True)

    reference_files = pdf_names(reference)
    stats = MoveStats()

    for pdf in sorted(source.iterdir()):
        if not (pdf.is_file() and pdf.suffix.lower() == PDF_EXTENSION):
            continue

        if pdf.name not in reference_files:
            stats.skipped_missing += 1
            logging.debug("Skipping %s (no match in reference).", pdf.name)
            continue

        destination_path = destination / pdf.name
        if destination_path.exists():
            stats.skipped_conflict += 1
            logging.warning(
                "Destination file already exists, skipping move: %s",
                destination_path,
            )
            continue

        logging.info("Moving %s -> %s", pdf, destination_path)
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        pdf.replace(destination_path)
        stats.moved += 1

    return stats


def main() -> None:
    args = parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    output_dir = args.output_dir.resolve()
    reference_dir = args.reference_dir.resolve()
    destination_dir = (
        args.destination.resolve()
        if args.destination
        else output_dir.parent / "02_matched_pdfs"
    )

    logging.info("Output directory: %s", output_dir)
    logging.info("Reference directory: %s", reference_dir)
    logging.info("Destination directory: %s", destination_dir)

    try:
        stats = move_matching_pdfs(output_dir, reference_dir, destination_dir)
        stats.log_summary()
    except Exception:
        logging.exception("Processing aborted due to an unrecoverable error.")


if __name__ == "__main__":
    main()
